2022-06-03 17:41:37,680 - custodian.policy - INFO - policy:sg-add-permission resource:security-group region:ap-southeast-2 count:0 time:0.56
2022-06-03 17:41:50,187 - custodian.policy - INFO - Provisioning policy lambda: sg-add-permission region: ap-southeast-2
2022-06-03 17:41:50,399 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/c7n/policy.py", line 518, in provision
    return manager.publish(
  File "/usr/local/lib/python3.9/site-packages/c7n/mu.py", line 387, in publish
    result, changed = self._create_or_update(
  File "/usr/local/lib/python3.9/site-packages/c7n/mu.py", line 458, in _create_or_update
    assert role, "Lambda function role must be specified"
AssertionError: Lambda function role must be specified
2022-06-03 17:56:46,296 - custodian.policy - INFO - Provisioning policy lambda: sg-add-permission region: ap-southeast-2
2022-06-03 17:56:46,627 - custodian.serverless - INFO - Publishing custodian policy lambda function custodian-sg-add-permission
2022-06-03 18:02:17,429 - custodian.policy - INFO - Provisioning policy lambda: sg-add-permission region: ap-southeast-2
2022-06-03 18:19:42,530 - custodian.policy - INFO - Provisioning policy lambda: sg-add-permission region: ap-southeast-2
2022-06-03 18:46:31,099 - custodian.policy - INFO - Provisioning policy lambda: sg-add-permission region: ap-southeast-2
2022-06-03 18:46:31,381 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/c7n/policy.py", line 518, in provision
    return manager.publish(
  File "/usr/local/lib/python3.9/site-packages/c7n/mu.py", line 387, in publish
    result, changed = self._create_or_update(
  File "/usr/local/lib/python3.9/site-packages/c7n/mu.py", line 460, in _create_or_update
    existing = self.get(func.name, qualifier)
  File "/usr/local/lib/python3.9/site-packages/c7n/mu.py", line 592, in get
    return resource_exists(
  File "/usr/local/lib/python3.9/site-packages/c7n/mu.py", line 598, in resource_exists
    return op(*args, **kw)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 745, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the GetFunction operation: The security token included in the request is expired
2022-06-03 18:49:31,926 - custodian.policy - INFO - Provisioning policy lambda: sg-add-permission region: ap-southeast-2
